spring.application.name=makemytrip
spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.data.mongodb.uri=mongodb+srv://dhanvanth:dhanvanth2026@makemytrip.ql4nagg.mongodb.net/makemytrip?retryWrites=true&w=majority